### ISSUE TITLE
Rando post game progression display. 

### ISSUE THREAD

**Issue by fatihG** [TalicZealot/SotnRandoTools#10]
# Is your feature request related to a problem? Please describe.
Nope.

# Describe the solution you'd like
Post game, show the path the player has taken to finish the seed. 
Record the deaths/resets, the relics that were picked up, etc. 

Similar to how Zelda Breath of the Wilds Hero's Path mode.
https://www.youtube.com/watch?v=t02p9LXGnpw

# Describe alternatives you've considered
And alternative would be to use something like a heatmap, though it wouldn't necessarily show you -how- you played but it would show you where you spent/wasted the most time at.

# Additional context
In the setting of a race with commentary by a third party, for example a Rando Tournament, having a quick post game discussion with the players path showing on screen could be a handy tool to quickly recap what went down. 

# Name suggestion
**ίχνος > íchnos** 
Greek word for 'trace'.

**Comment by TalicZealot** [comment]
The Tracker now supports saving replays, which can be replayed at https://taliczealot.github.io/replays/
Repository for the player: https://github.com/TalicZealot/SotN-Replay-Player

**Comment by Gods666thChild** [comment]
This was huge and changed SOTN racing forever. Great suggestion and great implementation.
