### ISSUE TITLE
[KHAOS EFFECT] - Allow user to add a min / max modifier to random stats as a setting OR pure-reroll toggle.

### ISSUE THREAD

**Issue by Ziggypigster** [TalicZealot/SotnRandoTools#14]
Would it be possible to include the ability to add a floor / cap to the percent modifier of the random stat commands that the khaos runner can change in the settings?
Or alternatively an option to only purely re-roll stats with no +/- modifiers (only a redistribution).

The current concern is that it can result in level 1 stats on high level characters with no way to regain stats since the player does not delevel. This currently makes this option stronger than weaken when used multiple times in a row due to the current random roll weighting (which is neat when looking for that specific challenge, but not always wanted / may not be clear to new viewers or players this can happen).

**Comment by TalicZealot** [comment]
Khaos Stats has been rewritten for more consistency, potential positive or negative bonus has been reduced. Will continue to monitor behavior.
