### ISSUE TITLE
Streamlabs Chatbow - Allow user to enable / disable Script Khaos Commands as a checkbox option per command

### ISSUE THREAD

**Issue by Ziggypigster** [TalicZealot/SotnRandoTools#15]
The Streamlab Chatbox should have a checkbox to enable / disable Khaos commands from appearing in the Index HTML Overlay file maintained by the Khaos Bot scripts.

There are certain seeds (ex. Adventure) where users may not want the full range of options (ex. krelics, pandora) but may still want them for other seed types.

Only current alternatives are to directly comment out / remove commands in the python file in between runs or to set price / cooldown as high as possible.

**Comment by TalicZealot** [comment]
Added in 1.0.7
