### ISSUE TITLE
[KHAOS EFFECT] Change cape colour

### ISSUE THREAD

**Issue by luccasbonato** [TalicZealot/SotnRandoTools#18]
# Name
Change cape colour

# Description
Literally change the cape colour by using the command and passing the 3 arguments of RGB next to it. Also If you found out to make it a changing colour like the twilight cloack, it would also be nice as a option.

# Duration
Until gets changed

# Example
I'm not aware if there is.

**Comment by TalicZealot** [comment]
With the exception of Joseph's Cloak cape colors and data are loaded dynamically, so at least for now I can't do this easily.

**Comment by Gods666thChild** [comment]
There was a conversation about potential personalization within the tracker tools in terms of people choosing their own cape colours to reflect themselves and, dare I say, style. If I'm understanding it correctly it'd be a pain in the ass to do for every cloak. But if users could choose their RBG within the tracker UI under something like personal settings then it would be up to the player/seed to find/equip Josephs Cloak. This may be too much effort for only a handful of people to use.
