### ISSUE TITLE
[KHAOS EFFECT] Nuke Bomb

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#19]
# Name
!knuke

# Description
Triggers a single neutron bomb that deals around 1000 damage to enemies currently on-screen. Additionally change the explosion effect palette to a warmer color to make it easy to differentiate from a regular neutron bomb if possible.

# Duration
Instant trigger

**Comment by TalicZealot** [comment]
There is potential to implement something similar to this. Bomb effects though require loading from the disc, but there are some alternatives. Could do a big Nuke or a more mild effect for a short duration, sort of a Turn Undead.

**Comment by TalicZealot** [comment]
Implemented with the Guardian Spirits Khaos Status.
