### ISSUE TITLE
[KHAOS EFFECT] Subweapons Only 

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#2]
# Name
subsonly

# Description
Alucard can only use subweapons for a limited time. Gives Cube of Zoe if the player doesn't already have it as well as a certain amount of hearts if the current amount is below a certain threshold for that duration.

# Duration
3 minutes or so

# Example
---

**Comment by TalicZealot** [comment]
Will look into this soon. Three minutes is a very long time for this game though.

**Comment by TalicZealot** [comment]
Subweapons Only has been added in 0.1.3
