### ISSUE TITLE
Default Sounds To Stereo

### ISSUE THREAD

**Issue by Gods666thChild** [TalicZealot/SotnRandoTools#23]
# Is your feature request related to a problem? Please describe.
Not a problem per se. But would be nice to enjoy the sound effects and music in it's best possible quality.

# Describe the solution you'd like
Freeze address 8003CAFC to 0000 (I think this is the right one)

# Describe alternatives you've considered
Some of us are doing it manually during library card check, before death take away our equipment and can be avoided by it being default.

# Additional context
From what I've been told, the game only defaulted at mono because when the game was released in the late 90s not all televisions were capable of stereo audio. So the default was set to mono and the option available to those who were capable. It's 2022 and some of these tracks sound much better as they were intended.

**Comment by TalicZealot** [comment]
Doing that doesn't actually signal to the CD player to output stereo, the user still has to navigate to the sound menu, then close it. Will see if I can find an alternative solution.

**Comment by TalicZealot** [comment]
Implemented in: 97753bfce48ce887537d63f01e241a7a08e43b41
