### ISSUE TITLE
Increased Height To Axe Lord Armour

### ISSUE THREAD

**Issue by Gods666thChild** [TalicZealot/SotnRandoTools#24]
# Name
Unable to think of command suggestion. !dutycalls is the dumbest name I can think of if its possible to transform into the armour in real time.

# Description
Increasing the jump height limit to the Axe Lord Armour at least to the normal height limit of Alucard. It brings the armour back to life with fun and functionality to be able to platform. I originally thought of a height closer to Leap Stone because I'm not personally sure on how quickly Axe Lord Armour descends relative to Alucard's descension, but obviously not a height that can be abused to break any logic etc.

# Duration
Unsure. See below.

# Additional Context
While I originally liked to have seen this as an addition to the randomizer as a whole, I'm unsure of if mouse would approve this, assuming my presumption of his intention of maintaining the integrity of the original game intentions. It would be at least cool to see it in action in Khaos in some form. (If I remember Axe Lord Armour can be troublesome to force in certain situations so I'm hoping there can be some implementation of some sort)

**Comment by TalicZealot** [comment]
I've mostly figured out how to make it jump an appropriate height, but the more I'm digging the more I think this is not worth it. It is so stiff and awful feeling. It might be better to take a different approach.

**Comment by TalicZealot** [comment]
Closing this, but I may make a small lua script that makes the axe lord challenge run possible.

**Comment by Gods666thChild** [comment]
> Closing this, but I may make a small lua script that makes the axe lord challenge run possible.

i would love to try that challenge if it gets made
