### ISSUE TITLE
[KHAOS EFFECT]

### ISSUE THREAD

**Issue by zeUltraspec** [TalicZealot/SotnRandoTools#25]
# Name
KHAOS ITEM CRASH

# Description
Activates a random item crash; either a Holy Cross, Hydro Storm, Spiral Axe, and item crashes for Agunea, Bible, and Rebound Stone. The item crash effects will damage all enemies and Alucard.

# Duration
Instant

# Example
Castlevania: Symphony of the Night

**Comment by TalicZealot** [comment]
Not currently possible as those effects are not loaded into memory in Alucard mode.
