### ISSUE TITLE
Situational Missing Relic Location On Map

### ISSUE THREAD

**Issue by Gods666thChild** [TalicZealot/SotnRandoTools#27]
https://www.twitch.tv/videos/1455301129

During the race, a player library carded before death. Once they finished library and entered Outer Wall, the Cube of Zoe check was not visible on the map. (Normally we all know to go back to entrance but the player relied on the map for their next decision)

The only information I have is that it was gokublack who experienced this. I do not know their current versions of tracker or bizhawk.

**Comment by TalicZealot** [comment]
The location was there, but the availability color wasn't shown yet due to not collecting a progression relic and reloading a bin without closing the tools. That part will be resolved next version.
