### ISSUE TITLE
Tool does not work with SOTN.io generated bin files

### ISSUE THREAD

**Issue by Jwguy** [TalicZealot/SotnRandoTools#28]
# Bug description:
Uploaded my SOTN .bin to SOTN.io, had it randomize. Confirmed it works and is randomized. Followed the instructions for setup including making sure the file tree is accurate, and attempted to load the tool via Tools -> External Tools. Bizhawk 2.9.1 shows "This tool doesn't work with this game."

# How to reproduce:
As above. I attempted to check the tool a various points, such as at the title screen, post-Richter, and post-Death. None were successful.

# SotnRandoTools version:
1.5.4

# BizHawk version:
2.9.1

# Seed Information:
Safe, Tournament disabled.

# Randomizer version:
3.15.0

# Operating system and version:
Windows 10 Pro, ver. 22H2

**Comment by Jwguy** [comment]
![SOTNToolsIssue](https://user-images.githubusercontent.com/16468732/236948320-bb3d0efa-c40c-4464-bf85-0cc82392b431.png)

Here's a screenshot, if it helps. It wouldn't let me upload the main issue with it, for some reason.

**Comment by TalicZealot** [comment]
Unrelated to the radnomizer. At the bottom left corner of BizHawk you see a question mark, this means that particular rom isn't recognized as a good rip. With a good one you will see a green check mark and the tools will work.
