### ISSUE TITLE
Bat-Master Location not tracked

### ISSUE THREAD

**Issue by regisritta** [TalicZealot/SotnRandoTools#29]
Hi. I don't know how to do this correctly so I'll just drop this comment here. 

I was playing a Bat-Master seed (1685247155595) with Area Randomizer active and one of the Vlad Locations was on the Forbidden Library, behind the bookcase where a Badelaire is on the vanilla game. This location wasn't marked on the tracker. Is this normal or did the rando had some change recently?

**Comment by TalicZealot** [comment]
Yes this is something that I will include with the next version. There used to be an old version of bat master which later got removed from both the rando and tracker.

**Comment by TalicZealot** [comment]
Implemented with 1.5.5
