### ISSUE TITLE
[KHAOS EFFECT] Invert Enemy Resistances

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#3]
# Name
invertres

# Description
Takes the vanilla resistances of all in-game enemies and inverts them. What was weak to light becomes resistant to it, resistant to dark becomes weak to it...

# Duration
Not sure

# Example
---

**Comment by TalicZealot** [comment]
Closing this since it got achieved by your romhack, I might still do _something_ with resistances, but this definitely fits more as a romhack.
