### ISSUE TITLE
Location marked incorrectly on map

### ISSUE THREAD

**Issue by regisritta** [TalicZealot/SotnRandoTools#30]
On the map using the Expedition and Adventure presets (without tournament mode enabled. Didn't test with it enabled yet) the marked locations are from the Spread locations instead of the Equipment locations.

RandoToolsVersion 1.5.8

Randomizer Version 3.15.0

BizHawk Version 2.8

Rolling back to 1.5.6 and 1.5.7 works like normal.

**Comment by TalicZealot** [comment]
Should be resolved in 1.5.9
