### ISSUE TITLE
Auto-Tracker does not un-light spike breaker armor if old save loaded

### ISSUE THREAD

**Issue by DocRandulf** [TalicZealot/SotnRandoTools#31]
# Bug description:
Acquired Spike Breaker armor (it lit properly in the auto-tracker when acquired) then died and game-overed before saving. Reloaded last save before Spike Breaker was acquired and it remained lit in the tracker despite the armor not being in inventory.

# How to reproduce:
Run SotnRandoTools w/Auto Tracker enabled.
Acquire Spike Breaker.
Die and Game Over without saving after acquiring Spike Breaker.
Reload last save.
Check Inventory to see no spike breaker, and if the icon is lit in the tracker.

# Additional context, screenshot or log file from /ExternalTools/SotnRandoTools/Logs/:
Screenshot shows Spike Breaker lit in tracker, but not it is not in inventory.
![image](https://github.com/TalicZealot/SotnRandoTools/assets/86634950/83e82d0a-02b0-48da-9b98-1d91911f9f01)

# SotnRandoTools version:
1.5.9

# BizHawk version:
2.9.1

# Seed Information:
1695053115870(safe) Safe Template

# Randomizer version:
Found in the file select menu of your randomized game.

**Comment by DocRandulf** [comment]
In Retrospect, the template uses randomized equipment, so that might have something to do with it.

**Comment by TalicZealot** [comment]
I see why it's happening, unrelated to randomized equipment stats. Will resolve in the next release, for now keep it in mind.

**Comment by TalicZealot** [comment]
Should be addressed in 1.6.0
