### ISSUE TITLE
Tracker map shows Guarded locations for OG seed

### ISSUE THREAD

**Issue by MainMemory** [TalicZealot/SotnRandoTools#33]
# Bug description:
The tracker's map seems to show the locations for the Guarded set even when playing an OG seed.

# How to reproduce:
Generate an OG seed, start playing with the tracker enabled, and open the map.

# Additional context, screenshot or log file from /ExternalTools/SotnRandoTools/Logs/:
![image](https://github.com/TalicZealot/SotnRandoTools/assets/6082665/1c1357de-0120-46c4-a9d0-a5a5618af652)

# SotnRandoTools version:
1.6.0
# BizHawk version:
2.9.1
# Seed Information:
https://discord.com/channels/407759960588419073/564738749678878720/1160600421103055048

# Randomizer version:
3.15.0

# Operating system and version:
Windows 10 Pro 22H2

**Comment by TalicZealot** [comment]
Will publish fix tomorrow. This was a crazy bug, one character difference due to boolean type coercion: "false" vs "False".

**Comment by TalicZealot** [comment]
Fixed in 1.6.1
