### ISSUE TITLE
Glitch preset shows incorrect tracker

### ISSUE THREAD

**Issue by DoozyzooD** [TalicZealot/SotnRandoTools#35]
When I open rando tools tracker in glitch preset, i get guarded map locations on the map instead of equipment

**Comment by TalicZealot** [comment]
Can you please provide a PPF, I can't generate glitch in a reasonable amount of time on my PC.

**Comment by DoozyzooD** [comment]
[Glitch-1697570300615.zip](https://github.com/TalicZealot/SotnRandoTools/files/12975643/Glitch-1697570300615.zip)

**Comment by TalicZealot** [comment]
Fixed in 1.6.2

**Comment by DoozyzooD** [comment]
Thanks Talic
