### ISSUE TITLE
Can we please have Aperture added into the tracker?

### ISSUE THREAD

**Issue by eldri7ch** [TalicZealot/SotnRandoTools#36]
I am attaching the JSON for Aperture, which significantly changes the logic of the castle. There are some issues where the tracker, because it assumes no changes to the tile maps of the castle are happening, says that certain checks are our of logic when, in fact, they are not even accessible at all. 

Example: There is a Jewel of Open door at Skill of Wolf. The tracker reads the file and sees that Jewel of Open is required in logic but "knows" that Skill of Wolf can be accessed with only Gravity Boots. If a player has Gravity Boots, the tracker marks the check as an 'out of logic' check because the logic of the JSON doesn't 100% match the vanilla layout of the castle.

I don't expect the tracker to be able to read tile and entity edits directly from the JSON, so if asking for the Out of Logic issue to be resolved is beyond reason, I don't mind. I would settle for just having the JSON distributed with the tracker, in the Presets folder.

![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/912bfb23-c032-4022-be92-8a4575a5c8f9)

[aperture.json](https://github.com/TalicZealot/SotnRandoTools/files/13184509/aperture.json)

**Comment by TalicZealot** [comment]
The tracker makes no assumptions other than reading locks, so this must be a bug. Will look into it.

**Comment by TalicZealot** [comment]
Since at this point this is a straight up romhack not just a randomizer I can't dynamically generate out of logic locks or it will break something like Force of Echo. I will have to turn them off display for non-native presets. Unless you encode that into the preset with another array.

**Comment by TalicZealot** [comment]
No no no, exact same thing as the existing lockLocation array, except those locks would be the allowed out-of-logic checks and ignored by the randomizer.

**Comment by eldri7ch** [comment]
OK, so a separate array that is ignored by the randomizer and identifies what the out of logic for each check would be. That's a great idea.

**Comment by TalicZealot** [comment]
The way I do allowed checks is by simply parsing the speedrun preset, which works for all non-romhacky presets.

**Comment by eldri7ch** [comment]
Let me throw something together and I'll attach the new file.

**Comment by eldri7ch** [comment]
If the minimum requirement for the check means that there is no out-of-logic, do I just leave the logic the same as in the "lockLocation" list?

**Comment by TalicZealot** [comment]
I would leave it blank, but it would have the same effect.

**Comment by eldri7ch** [comment]
[aperture.json](https://github.com/TalicZealot/SotnRandoTools/files/13191754/aperture.json)

This has the "lockLocationAllowed" section at the bottom. It should be noted that Granfaloon is out of logic with 0 relics in this preset. I left the requirements that were required for each new check where they are in the normal list in case that helps.

**Comment by TalicZealot** [comment]
Can you send over a ppf so that I can do some testing.

**Comment by eldri7ch** [comment]
[Aperture-PlatinumLeviathan48.zip](https://github.com/TalicZealot/SotnRandoTools/files/13192005/Aperture-PlatinumLeviathan48.zip)

**Comment by TalicZealot** [comment]
Why did you add Holy Glasses to all the allowed checks in 1st castle? Other than that it seems to work as intended.

**Comment by TalicZealot** [comment]
By the way this branch was meant to be used with open, in my testing it worked fine. https://github.com/TalicZealot/SotN-Randomizer/tree/randomize-starting-location

**Comment by TalicZealot** [comment]
Added in 1.6.3

**Comment by eldri7ch** [comment]
> Why did you add Holy Glasses to all the allowed checks in 1st castle? Other than that it seems to work as intended.

I might have been hungry and not paid attention. Do I need to send an updated file?

**Comment by TalicZealot** [comment]
It's live so you can test it locally.

**Comment by eldri7ch** [comment]
I just loaded a seed and it's pulling the incorrect logic for Demon Card, Leap Stone, Form of Mist, and Merman Statue. They should be in logic at layer 0. Mormegil is out of Logic at Layer 0 and that is correct.
![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/4d22e7be-8b82-40ca-9995-d9181ac9683b)

**Comment by eldri7ch** [comment]
Would it help if I outright removed _new_ layer 0 checks in the Allowed section?

**Comment by TalicZealot** [comment]
I would have to see the preset file.

**Comment by eldri7ch** [comment]
[aperture.json](https://github.com/TalicZealot/SotnRandoTools/files/13193188/aperture.json)

**Comment by TalicZealot** [comment]
Oh they are missing completely, yes add them to "lockLocation" with an empty lock.

**Comment by eldri7ch** [comment]
They're already added there. 
![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/98b580d1-4928-44a1-8b55-9a7c37512523)

**Comment by TalicZealot** [comment]
I see what's going on, gonna patch it.

**Comment by TalicZealot** [comment]
Ok this should be it this time.

**Comment by eldri7ch** [comment]
Thanks! Works great!
