### ISSUE TITLE
Additional checks requested to be added for "Tourist" relic extension.

### ISSUE THREAD

**Issue by eldri7ch** [TalicZealot/SotnRandoTools#37]
# Is your feature request related to a problem? Please describe.

Not related to a problem with the tools as they are designed to function

# Describe the solution you'd like
A clear and concise description of what you want to happen. Please remember to search for similar issues before writing anything, including in closed issues!

I would like to add thirteen new checks to the randomizer and have them supported by the tracker.

# Describe alternatives you've considered

I do not believe there are alternatives since the checks I am adding have never been added to any randomizer preset before.

# Additional context

Attached image showing locations and a copy of my extension.js and casual.json showing the check locations.

![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/e01c57b6-b4d0-482f-95d7-5bb4bdf62a69)

[extension_js.zip](https://github.com/TalicZealot/SotnRandoTools/files/13709106/extension_js.zip)
[casual_json.zip](https://github.com/TalicZealot/SotnRandoTools/files/13709111/casual_json.zip)

**Comment by TalicZealot** [comment]
I could, but this is another case where it's stepping outside of the scope of the original Randomizer, so individually adding support for features like this isn't very practical or the goal of this tool. Maybe I can add another system to parse custom locations. 

To do that the json would have to provide an array of the new custom locations and their info.
For example:
`
"customLocations": [{
    "location": "Bekatowa",
    "row": 38,
    "col": 111,
    "rooms": [
        {"address": "0x06BC61", "values": ["0x01","0x04"]},
        {"address": "0x06BC51", "values": ["0x01","0x04"]}
    ]
  }]
`

The rooms array is a list of rooms on the minimap in ram, from which the location can be checked or peaked. The values need to be checked manually by assessing what positions are reasonable for peeking and which ones could be problematic. Sometimes compromises are necessary.

**Comment by eldri7ch** [comment]
Why are there two instances of "{"address": "0x06BC61", "values": ["0x01","0x04"]}"? Is that simply to offer example that multiple rooms could be required for a single check?

**Comment by TalicZealot** [comment]
A location can potentially be checked or peeked from multiple rooms on the map. Those are two different rooms, the second address ends in 0x51. The map in ram is actually not represented in bytes but nibbles (half bytes) and each nibble has 4 bit toggles per quadrant of uncovered map, so there can be multiple values that represent a checked or peeked location that needed to be accounted for. This could also be done with bit mask checks, but it hasn't been necessary for me to convert everything to that.

**Comment by eldri7ch** [comment]
OK, I will assemble that, then. Thanks for the explanation.

**Comment by eldri7ch** [comment]
OK, so how would that work, then, if the preset file I am using is inheriting the checks from Casual or Nimble? Should I just include the "customLocations" language in the preset files utilizing the extension?

**Comment by TalicZealot** [comment]
Oh I see what you mean, I totally forgot about how the extensions are defined. Hmmm I guess this doesn't work then.

**Comment by TalicZealot** [comment]
I just don't want to commit to adding stuff like this manually every time. You might test these and it could turn out that half of them are dumb and need replacing.

How about this: For a custom extension make a json with that name holding the customLocations array. That would need to be put in the tracker presets folder. When the tracker sees an extension it doesn't recognize it will look there. So in this case it would be `tourist.json`.

**Comment by eldri7ch** [comment]
That's a great idea. Will do.

**Comment by eldri7ch** [comment]
Trying to research how to get the data needed for this, what does row and column refer to? I can get the map coordinates and the values, but the row and column are throwing me off.

**Comment by TalicZealot** [comment]
Those are coordinates to a room quadrant in GPU ram. I think I used to have an easy way of calculating that by referencing the map image, but I don't remember at the moment. I will check tomorrow. If you want to play around with it the map texture starts at `0x08AE80` and every row is offset by 0x800, where every byte colors two pixels. So it must be something like get the raw 240x80 map and measure the center of the room then divide the x by 2.

**Comment by TalicZealot** [comment]
I've decided that my old way of doing those coordinates is really stupid, because it goes all the way back to the Lua tracker when I really didn't understand what was going on. So I'm going to be changing it to simply x,y coordinates on the map texture and I'll do any necessary math in code. Location coordinates will reflect the top left pixel of the room or pixel of the location (for equipment locations). Here are reference images of the map textures with increased visibility:
![normal](https://github.com/TalicZealot/SotnRandoTools/assets/18632109/b0f720fe-15db-498b-b029-e6707be1cafe)
![inverted](https://github.com/TalicZealot/SotnRandoTools/assets/18632109/5e55cd6e-09e5-4351-8e46-12be16069b47)

**Comment by eldri7ch** [comment]
I will move forward with this, then.

**Comment by eldri7ch** [comment]
When looking for "Values" Are you asking for all related values or just the bit that refers to that specific room? 

so do you need this: `"values": ["0x55","0x05","0x01"]` or would just `"values": ["0x01"]` suffice since only one bit needs to be calculated as filled?

**Comment by eldri7ch** [comment]
Anyway, here's the file

[tourist.json](https://github.com/TalicZealot/SotnRandoTools/files/13797112/tourist.json)

**Comment by TalicZealot** [comment]
> or would just `"values": ["0x01"]` suffice

Yes that is enough for cases when that is the only viewable position.
Send over a ppf and I will test everything later today.

**Comment by TalicZealot** [comment]
Actually never mind, don't need a PPF because I realized this should also be possible for custom seeds, so I changed the settings a bit to allow for that. Another thing that might be a good idea to support would be if the checks should be shown as rooms or locations on the map like for equipment. This seems correct to me:
![test](https://github.com/TalicZealot/SotnRandoTools/assets/18632109/b8c3f571-a958-4b77-9074-dcbb4cd0a765)

**Comment by eldri7ch** [comment]
Perfect!

**Comment by TalicZealot** [comment]
Implemented in 1.6.5

**Comment by eldri7ch** [comment]
How will "Out of Logic" be handled? Just add the new checks in "lockLocationsAllowed" to the json files using those checks?

**Comment by TalicZealot** [comment]
I don't parse logic inheritance at all. With the base presets I don't have to since casual and speedrun are baselines. For custom locations you would need to provide that information in the preset.

**Comment by TalicZealot** [comment]
Alternatively you can add them to the speedrun preset, that's what I did to accommodate equipment locations.

**Comment by eldri7ch** [comment]
I did add them there, so if I move that JSON over, it will add their OOL to the tracker?

**Comment by TalicZealot** [comment]
The standard Out of Logic locks are grabbed from the speedrun preset and the normal locks from casual. Preset locks are loaded on top of that and can overwrite the defaults.

**Comment by eldri7ch** [comment]
Then everything should be good!

**Comment by eldri7ch** [comment]
The map doesn't accurately reflect the requirements for the checks. Also, it should be including the equipment checks. The only way to make it so that tourist didn't also increase the number of checks in Equipment was by ordering them so that Tourist also included all of the equipment checks.

Here are the files for Tourist, Casual, and Grand Tour which are the files involved.

[grand-tour.json](https://github.com/TalicZealot/SotnRandoTools/files/13846961/grand-tour.json)
[casual.json](https://github.com/TalicZealot/SotnRandoTools/files/13846962/casual.json)
[tourist.json](https://github.com/TalicZealot/SotnRandoTools/files/13846967/tourist.json)
![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/fd76ca69-5733-422b-bb73-2a52601b430e)

**Comment by eldri7ch** [comment]
Here is a Grand Tour ppf in case it's needed.

[Grand-Tour-MandalorianBus92.zip](https://github.com/TalicZealot/SotnRandoTools/files/13847027/Grand-Tour-MandalorianBus92.zip)

**Comment by TalicZealot** [comment]
> Also, it should be including the equipment checks. The only way to make it so that tourist didn't also increase the number of checks in Equipment was by ordering them so that Tourist also included all of the equipment checks.

I don't understand what you mean by that. Are you saying the tourist extension also includes all the equipment locations?

**Comment by TalicZealot** [comment]
The location `Colosseum Green tea` does not have consistent capitalization across files.

**Comment by eldri7ch** [comment]
OK, let me fix both of those

**Comment by eldri7ch** [comment]
[tourist.json](https://github.com/TalicZealot/SotnRandoTools/files/13850995/tourist.json)

Fixed

**Comment by TalicZealot** [comment]
Reworked and implemented in 1.6.6

**Comment by eldri7ch** [comment]
The tracker still shows no requirements for the additional checks. It shows the two in Chapel and Arena as well as the one in Caverns available to be checked with 0 relics.

**Comment by eldri7ch** [comment]
![image](https://github.com/TalicZealot/SotnRandoTools/assets/108695566/e9da17f4-1588-4402-813d-a2bc10cbf906)

It should be inheriting the check logic from Casual per the grand-tour.json. This is planned for simultaneous launch with an expedition-style preset that will inherit Nimble logic, so having the tourist.json inherit check logic from somewhere else isn't a good idea.

**Comment by TalicZealot** [comment]
Can you make sure these locations are named identically in `tourist.json`, `casual.json` and `speedrun.json`

**Comment by eldri7ch** [comment]
I'm the idiot. I went to do as you asked and realized that updating the tracker replaces the files in that folder with the native preset json. It works now. Thanks!

**Comment by TalicZealot** [comment]
Oh yeah I suppose it would, totally didn't think about that.
