### ISSUE TITLE
Tracker showing Guarded locations for an OG seed (again)

### ISSUE THREAD

**Issue by MainMemory** [TalicZealot/SotnRandoTools#38]
# Bug description:
When running an OG seed, the tracker correctly displays the seed name as OG, but the map shows Guarded locations such as Scylla and Granfaloon. This particular seed was generated with music randomization disabled, which may be relevant?

# How to reproduce:
Generate an OG seed, finish the prologue, and open the map.

# Additional context, screenshot or log file from /ExternalTools/SotnRandoTools/Logs/:
![image](https://github.com/TalicZealot/SotnRandoTools/assets/6082665/33f8880d-0fb3-4e5c-b301-5b1044d551aa)
![image](https://github.com/TalicZealot/SotnRandoTools/assets/6082665/f636e3e8-95f8-451f-bbfb-5301034785e6)

# SotnRandoTools version:
1.6.7
# BizHawk version:
2.9.1
# Seed Information:
https://discord.com/channels/407759960588419073/564738749678878720/1216094189360775299

# Randomizer version:
3.15.0

# Operating system and version:
Windows 10 22H2

**Comment by TalicZealot** [comment]
Every time I touch preset parsing I forget about this wack edge case. Will fix asap.

**Comment by TalicZealot** [comment]
Resolved in 1.6.8
