### ISSUE TITLE
[KHAOS EFFECT] Nightmare Damage

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#4]
# Name
nightmare

# Description
Every enemy and gimmick deals 3x the damage for a limited time.

# Duration
Not sure

# Example
---

**Comment by TalicZealot** [comment]
This is effectively achieved through the Poison status, Weaken / Super Weaken and the upcoming HnK action. I also have some ideas about making respawned bosses be stronger than the first fight.
