### ISSUE TITLE
Adding new checks form old extensions

### ISSUE THREAD

**Issue by eldri7ch2** [TalicZealot/SotnRandoTools#40]
# Is your feature request related to a problem? Please describe.
I would like to be able to add checks from other extensions into new extensions for the tracker. We created a new extension that utilizes check locations from equipment _but not all of the checks from equipment_. 

# Describe the solution you'd like
We can utilize the same format from when we worked on Tourist but, instead, we can use "watchindex" like the tracker uses instead of "address" because these checks are already in the tracker for other presets. I have attached an example.

# Describe alternatives you've considered
We could potentially use a format that just calles the old extension and the check name but I think this may require more work on the back-end.

# Additional context
[wanderer.json](https://github.com/user-attachments/files/15749182/wanderer.json)
[lookingglass.json](https://github.com/user-attachments/files/15749198/lookingglass.json)

[Lookingglass-SapphireBarbarian67.zip](https://github.com/user-attachments/files/15749190/Lookingglass-SapphireBarbarian67.zip)

If you need to know what this looks like in the randomizer, we have the latest version of the rando repo here:
https://github.com/eldri7ch2/SotN-Randomizer-Adv

**Comment by TalicZealot** [comment]
To make sure I understand this, **wanderer** doesn't actually extend equipment, but you want to conveniently use whichever locations you need from equipment.
I think I already meant to support this, but didn't do it all the way. All you should need is the location name. Then it can just tag the existing one and use it. I'll look into this over the next couple days and post here. I'm in the middle of rewriting the WebSocket server for the overlay so these will probably come out at the same time.

**Comment by eldri7ch2** [comment]
"To make sure I understand this, wanderer doesn't actually extend equipment, but you want to conveniently use whichever locations you need from equipment."

100% Correct.

**Comment by TalicZealot** [comment]
This will be the format when including pre-existing locations.
[wanderer.json](https://github.com/user-attachments/files/15807506/wanderer.json)

**Comment by eldri7ch2** [comment]
Perfect, thanks!

**Comment by TalicZealot** [comment]
While I'm here I will add a field to presets that allows you to change which relics are considered progression for people using the alternative display method like DinnerDog.
```
"progressionRelics": [
      "Demon Card", "Soul of Bat", "Spirit Orb"
    ]
```

**Comment by TalicZealot** [comment]
Would anything break if I shove this whole folder in the tracker? `https://github.com/eldri7ch2/SotN-Randomizer-Adv/tree/master/presets`

**Comment by eldri7ch2** [comment]
That folder is provided for both the randomizer and the tracker, so nothing will break. In fact, it would help.

**Comment by TalicZealot** [comment]
Implemented in 1.7.0.
I fully suspect that some hotfixes will be needed for this release.

**Comment by eldri7ch2** [comment]
[ToolsErrorMessage.txt](https://github.com/user-attachments/files/15826528/ToolsErrorMessage.txt)

Two users experienced issues trying to update the tools. Error message attached

**Comment by TalicZealot** [comment]
Updated files, they can download the update zip from [https://github.com/TalicZealot/SotnRandoTools/releases/tag/1.7.0](https://github.com/TalicZealot/SotnRandoTools/releases/tag/1.7.0)
