### ISSUE TITLE
JP Familiars separated from Eng in Rando

### ISSUE THREAD

**Issue by eldri7ch2** [TalicZealot/SotnRandoTools#41]
# Is your feature request related to a problem? Please describe.
I don't know if this affects the tools or not. It should be noted that we have separated the JP familiars from the English ones in the randomizer. 

# Describe the solution you'd like
I want to make sure that the rando tools will properly represent and enable co-op sending of JP familiars based on the "new" coding around them. Originally, these familiars appeared after the other familiars in the menu, then Konami patched them out. We undid the patch.

# Describe alternatives you've considered
Thi is simply a confiormation that both the Tracker and the Co-Op mode, specifically, will work with the new locations for these switches.

# Additional context
New GitHub repo and site.

https://github.com/eldri7ch2/SotN-Randomizer-Adv
https://sotnrando.net/

**Comment by TalicZealot** [comment]
The tools do not modify the switch menu in any way, so I don't see a reason for it to be a problem. As long as the original location of the relic flags remains the same as vanilla.

**Comment by eldri7ch2** [comment]
Nice. Good to know!
