### ISSUE TITLE
Presets not utilizing lockLocationAllowed and new extension errors

### ISSUE THREAD

**Issue by eldri7ch2** [TalicZealot/SotnRandoTools#42]
Please use this template for any bugs or problems you encounter using the tools and label the issue appropriately. Fill as many of the fields listed below as possible.

# Bug description:
All locations in custom logic presets are displayed as out of logic unless they are directly in logic.

One check in both the Wanderer and the Tourist extensions appears in the top right corner.

# How to reproduce:
Load any of the presets not available on SOTN.io that contain custom logic

# Additional context, screenshot or log file from /ExternalTools/SotnRandoTools/Logs/:
![image](https://github.com/TalicZealot/SotnRandoTools/assets/171279882/1c471414-ca18-4f83-b050-2705e51fe382)
![image](https://github.com/TalicZealot/SotnRandoTools/assets/171279882/83527d02-a514-444d-9930-2232084c0a2e)
![image](https://github.com/TalicZealot/SotnRandoTools/assets/171279882/e4bdce49-c90b-4848-b523-ce88036ec45d)
![image](https://github.com/TalicZealot/SotnRandoTools/assets/171279882/3a30e339-05ea-4f93-8a29-b24da3bbc3f4)

# SotnRandoTools version:
1.7.0

# BizHawk version:
2.9.1

# Seed Information:
[Preset PPF.zip](https://github.com/user-attachments/files/15858899/Preset.PPF.zip)
All JSON are available on my github for the randomizer

# Randomizer version:
3.16.0

# Operating system and version:
Win 10 22H2

**Comment by TalicZealot** [comment]
Does this looking glass screenshot seem accurate? 
![image](https://github.com/TalicZealot/SotnRandoTools/assets/18632109/61dcfe79-1b8a-4bfa-8fb3-5353d5608166)

**Comment by eldri7ch2** [comment]
Yes, so far.

**Comment by TalicZealot** [comment]
Should be fixed in 1.7.1

**Comment by eldri7ch2** [comment]
Good evening,

The tourist checks aren't clearing even when they're checked.

![image](https://github.com/TalicZealot/SotnRandoTools/assets/171279882/878eddfb-0f29-4ea1-9478-841b7d2bc52f)

**Comment by TalicZealot** [comment]
Ah ok I see, another side effect of me pre-adding locations from casual.
