### ISSUE TITLE
[KHAOS EFFECT] Shuffle Input Commands

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#5]
# Name
relearn

# Description
Randomizes which input command performs which spell.

# Duration
Permanent until shuffled again.

# Example
---

**Comment by TalicZealot** [comment]
No plans on manipulating inputs. I can see how it would be funny to watch, but it would mostly devolve to the player sitting there or ignoring spells. I don't want to negate the skill level people gained from practicing this harshly.
