### ISSUE TITLE
[KHAOS EFFECT] Enchanting the Banquet

### ISSUE THREAD

**Issue by Lakifume** [TalicZealot/SotnRandoTools#6]
# Name
succ

# Description
We all know that everyone loves hearing Enchanted Banquet, that's why it'll be playing as the in-game BGM for the next 5 minutes.

# Duration
5 minutes

# Example
---

**Comment by TalicZealot** [comment]
I can have the viewer select a song. Which would start the next time the game loads XA audio, any loading screen or entering a mute screen transition like a save. The Banquet meme kind of wore off, so I think having the option to also select cool tracks like Blood Relations can be neat.

**Comment by TalicZealot** [comment]
Version 1.1.8 introduces an action to pick the track for the next few minutes.
