### ISSUE TITLE
[Coop] Visual feedback when setting up for hosting or connecting.

### ISSUE THREAD

**Issue by fatihG** [TalicZealot/SotnRandoTools#7]
# Is your feature request related to a problem? Please describe.
It is not clear when currently starting Co-op, whether you are connected or not, either as a host or a client. 

# Describe the solution you'd like
When you click on host, grey everything else out and change the button to 'quit' or something similar. To end the session. 
That way you have visual feedback that something has happened. 

As a client connecting to a host. When you click the connect button, grey everything else out. 
Change the button to 'connecting'. and if the player has connected, change it to 'connected' for a bit and after a bit change it to 'disconnect'.

Not having feedback when using the main coop window but instead relying on the log window isn't user friendly at all. 
And considering most people that would use this aren't coders or whatever, making it easy for them should be a priority. 
(After getting all the functionality done of course.)

The solutions i have written above are far from ideal as well. 
It's just a quick way of getting -some- feedback, using the current 'design' of the tool. 

# Describe alternatives you've considered

# Additional context

**Comment by fatihG** [comment]
Oh, I am not sure if it is possible, but until you have time to implement that stuff a quick workaround for now would be to open the Log window from the rando tools window automatically. (If that is possible at all)

So if you launch Coop for example, it also automatically launches the log window. 
That way, until some proper feedback has been implemented, people that don't know how the tool works currently get a clue that the Log window is important. 

If not, adding a simple message, the moment you click on launch, that says something like : 'Make sure to open your Log window' could be added instead. And they would have to confirm the message. (maybe with a checkbox not to remind them again).

The easiest way though would be to just some static text at the bottom of the 'Coop Settings' tab.

![sotnRT](https://user-images.githubusercontent.com/4147356/114248876-37ca8f80-9999-11eb-88af-cf09d130e2d6.png)

**Comment by TalicZealot** [comment]
I've been going back and forth on how to handle notifications, but for now I've started implementing a system that is not in-game. Right now a lot of UI elements are placeholders until implementation is stable and set in stone.

**Comment by TalicZealot** [comment]
A new Co-Op form with UX improvements and status notifications have been added to 0.1.6
