### ISSUE TITLE
Notification separated from in game overlay

### ISSUE THREAD

**Issue by fatihG** [TalicZealot/SotnRandoTools#8]
# Is your feature request related to a problem? Please describe.
Not really a problem, just an option for people to separate the notifications from the in game overlay. 

# Describe the solution you'd like
Have a checkbox in the Khaos tool to enable/disable the in-game overlay. 
And make it somehow possible to read the last command in OBS itself, so it can be shown on your layout. 

# Describe alternatives you've considered
Have Khaos spit out a .txt file with the last used command. 
That way in OBS you can have a text source, reading the .txt that Khaos spit out. 
(similar to how streamlabs chatbot spits out a bunch of .txt files for use with OBS and text sources.)

A straight up plugin, for OBS, that reads or gets sent data from the Khaos Tool itself. 

# Additional context
It makes sense to have something pop up in the game so the streamer/player knows what is going on. 
But if someone wants to incorporate it in their layout in OBS somehow, make that possible as well.

**Comment by TalicZealot** [comment]
Implemented for the next release.
