### ISSUE TITLE
Clarity for the viewer as to what is going on with the Khaos Commands.

### ISSUE THREAD

**Issue by fatihG** [TalicZealot/SotnRandoTools#9]
# Is your feature request related to a problem? Please describe.
I have noticed a lot of confusion when it comes to the timers and cooldown for Khaos. 
Viewers thinking that their command didnt go through or it being skipped and other commands go through before theirs. 

# Describe the solution you'd like
A way to show what times or what the current cooldown for a specific command is. 
Either in the Khaos tool itself so it can be window captured or somehow in OBS itself. 

# Describe alternatives you've considered
It could probably be done through a chatbot as well. Something like warning if a command has already been triggered, or if a command is currently on a countdown. 

# Additional context
-

**Comment by TalicZealot** [comment]
Addressed through bot responses, in-game action timers and queue. The new command widget that comes with 1.0.0 works real-time and the new bot script allows me to continue improving clarity.
